### ISSUE TITLE
About the format of submission

### ISSUE THREAD

**Issue by GilgameshD** [sharathadavanne/seld-dcase2019#11]
Hi! I have one question that is not related to the code but the challenge submission.

I am a little confused about how to submit systems. How should I provide the results of both datasets (FOA and MIC)? For one submission, the name of the folder should be 'Adavanne_TAU_task3_**i**', where **i** represents the index of the system. So the results of both dataset should be provided in one submission?

**Comment by sharathadavanne** [comment]
Hi @GilgameshD each participant is allowed up to four different submissions per task. So ideally, you could submit GilgameshD_CMU_task3_1 for FOA and GilgameshD_CMU_task3_2 for MIC formats. You can accordingly update the metadata files (*.yaml) about your system details, where you mention which format of audio you chose for the corresponding results.

Did this answer your question? :)

**Comment by GilgameshD** [comment]
Thanks for your reply. So according to my understanding, each submission should provide the result of only one dataset (FOA or MIC). Is that right?

**Comment by sharathadavanne** [comment]
Yes. The idea is that each of the four submissions will have results of just one method/configuration. So if you have trained your method with just MIC, just FOA, or both MIC and FOA datasets your method will have one single output which you will submit as one submission.

**Comment by GilgameshD** [comment]
Thanks a lot for your kind reply!

**Comment by zjysteven** [comment]
@sharathadavanne I'm also experiencing a submission issue. The CMT system says that one could upload 1 to 3 zip files, with maximum file size of 20Mb. However, one system with 500 output files (400 for development and 100 for evaluation) already takes up about 16Mb. Then how am I supposed to submit four systems within one zip file as instructed by the submission page of DCASE2019? Thank you!

**Comment by sharathadavanne** [comment]
Dont worry @zjysteven :) I have asked the organizers to increase the file upload size restrictions. I will update you here when that happens (Alternatively, drop me an email, I can update you there aswell). Worst case we will figure out some way to get your results to us :)

**Comment by zjysteven** [comment]
@sharathadavanne Oh, great! Thanks for your help!

**Comment by sharathadavanne** [comment]
Hi @zjysteven try submitting now. The maximum file size has been increased to 100 Mb.

**Comment by zjysteven** [comment]
@sharathadavanne Have successfully submitted! Thanks again!
