### ISSUE TITLE
evaluation code 

### ISSUE THREAD

**Issue by suwoncjh** [sharathadavanne/seld-dcase2019#13]
Hi @sharathadavanne 

I have a question about the evaluation code. During the challenge period, I always evaluated my system using "calculate_SELD_metrics.py" script for the development dataset (four cross-validation splits)

So, my question is when you evaluate submitted systems, same "calculate_SELD_metrics.py" script will be used? 

Otherwise, I am afraid that there will be a gap with the results that I expected.

thank you.

**Comment by sharathadavanne** [comment]
Yes, the same script will be used for calculating evaluation scores.

**Comment by suwoncjh** [comment]
Thanks!
