### ISSUE TITLE
audio loading in the feature class

### ISSUE THREAD

**Issue by eshalev4** [sharathadavanne/seld-dcase2019#14]
Hi,

In line 96 in the audio loading function of the feature class, there is a division by 2^15 and some epsilon addition. Can you kindly expand on the reasoning of this operation?

**Comment by sharathadavanne** [comment]
Hi, the 2^15 is to convert the short int values of wav which is in the range [-32768 to 32767] to float range of  [-1 to 1]. The epsilon is to handle any zero values in the audio, but not really necessary you can ignore it.

**Comment by eshalev4** [comment]
Thanks
