### ISSUE TITLE
Last block is omitted in the f1 calculation 

### ISSUE THREAD

**Issue by eshalev4** [sharathadavanne/seld-dcase2019#15]
In metrics/evaluation_metrics.py, line 209. the following operation `new_size = int(np.ceil(O.shape[0] / block_size))` results in ommitting the last block of the 1 sec segment.

Note that `O.shape[0] ` and `block_size` are integers, resulting in `O.shape[0] / block_size` floored to the closest integer and ommitting the fraction of the last block. It follows that the `np.ceil()` opration does nothing as well as the `int()` casting. 

I hope I made no mistake here or miss anything, these are the results I viewed using `print()` on my system. The following corrected the problem: `new_size = int(np.ceil(float(O.shape[0]) /float( block_size)))`

**Comment by sharathadavanne** [comment]
Thanks for pointing that out @eshalev4 
The current code works perfectly on Python3.x but has the problem you mentioned for Python2.x. 
Just heads up, I am doing all the development and evaluation on my end using Python3.x. I wanted the code to be usable for people using Python2.x, but I seemed to have overlooked this.
I will fix the same. Cheers.
