### ISSUE TITLE
Sound source localisation in ODAS library

### ISSUE THREAD

**Issue by raikarsagar** [sharathadavanne/seld-dcase2019#16]
Hi, thank for systematic repo. Are you aware of ODAS library for microphone array based sound source localisation and tracking? Is it the same implementation which has gone in ODAS as well?

Thank you

**Comment by sharathadavanne** [comment]
Hi @raikarsagar this repo is in no way connected to ODAS. This is an entirely deeplearning based approach for source detection and localization of static sources. For studies on dynamic sources including tracking them please refer to my other repo - https://github.com/sharathadavanne/seld-net
