### ISSUE TITLE
question about  the "Results for the development dataset"

### ISSUE THREAD

**Issue by suwoncjh** [sharathadavanne/seld-dcase2019#3]
I have a question about the "Results for the development dataset"  as below 
-----------------------------------------------------------------------
Dataset     | Error rate | F score | DOA error | Frame recall
Ambisonic | 0.34 | 79.9 % | 28.5° | 85.4 %
Microphone array | 0.35 | 80.0 % | 30.8° | 84.0 %
-----------------------------------------------------------------------

Is this result for the evaluation set which is not currently available?

or average results of the 4 cross-validation test at each split.

If so, how can I calculate the entire one results using 4-fold validation results?

thanks.

**Comment by sharathadavanne** [comment]
Hi @suwoncjh the results are for the 4 cross-validation set. You can obtain similar results by doing the steps described [here](https://github.com/sharathadavanne/seld-dcase2019#training-the-seldnet). Specifically for the Ambisonic format, you will have to run `python seld.py 2` for microphone array results and `python seld.py 4` for Ambisonic results. This will dump all the file-wise results into a folder, from which the average results for the four cross-validation scores similar to the results you shared can be obtained using the `calculate_SELD_metrics.py` script

**Comment by suwoncjh** [comment]
thanks @sharathadavanne 

I will check.
