### ISSUE TITLE
Question about the challenge rules

### ISSUE THREAD

**Issue by suwoncjh** [sharathadavanne/seld-dcase2019#4]
Hi @sharathadavanne 

In the baseline system, SELDnet estimates the direction of arrival and detects the sound events jointly. 

BTW, Is it possible to make two separate models for each task?  For example, there are two separate neural networks models (one for localization and one for detection) in one integrated system. 

Finally, Is it possible to use a model-based approach for localization task (SPR-PHAT, MUSIC,...); (In this case, we use the neural network model just for the sound event detection task)

Because this is my first-time DCASE challenge, I am not make sure about the challenge rules.

**Comment by sharathadavanne** [comment]
Yes @suwoncjh you can use multiple deep neural network models for the individual sub-tasks of detection and localization, you can also use model-based approaches. Additionally, based on your approach you can use the suitable  Ambisonic or microphone array format audio.  But make sure the results of the method you submit is in the [format required by the task](http://dcase.community/challenge2019/task-sound-event-localization-and-detection#submission).

**Comment by suwoncjh** [comment]
Thank you for your quick and clear answer. 👍  @sharathadavanne
