### ISSUE TITLE
how to import custom data?

### ISSUE THREAD

**Issue by bharatsubedi** [sharathadavanne/seld-dcase2019#5]
Hello @sharathadavanne 
Thank you for your great work.
I would like to know how can I build the model with my custom dataset.
I have small number of audio dataset around 35(audio clips) and angle of audio comming from source. Each audio file are from different user and different angles look likes 0,60,120,180 etc in json format.
![image](https://user-images.githubusercontent.com/14069935/56486953-7b116680-6514-11e9-8ed4-518ac3cbadcc.png)
Thank you

**Comment by sharathadavanne** [comment]
I have some questions.
Do all these 35 clips contain the same sound class? for example speech?
Within the clip, is the sound class active throughout? or only in some parts of the clip?
How long in duration are these 35 clips together? Deep learning methods might need larger datasets. If your dataset is small, I would recommend some parametric methods like [SRP](https://en.wikipedia.org/wiki/Steered-Response_Power_Phase_Transform) or [MUSIC](https://en.wikipedia.org/wiki/MUSIC_(algorithm)).

**Comment by bharatsubedi** [comment]
All audio file contains different speech and the sound also active throughout with higher noise.
The duration of the sound file is approximately 3 second. 
can you tell me how to fit in your network?
Thank you

**Comment by Qinstudy** [comment]
@sharathadavanne  @bharatsubedi   I have also been experimenting with custom datasets recently. I wonder if it is possible to use the 35 audio provided by bharatsubedi as an evaluation data set and then observe the prediction results.

**Comment by sharathadavanne** [comment]
@bharatsubedi I think the dataset you have is too small for using deep learning models. I would recommend using the parametric methods I suggested in my previous comment.
